name: Ejecutar mi código

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Configurar Node.js (ejemplo para Node.js)
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar el código
      run: npm run start
